title: Teach a Robot to Do Maths
description: UC Berkeley EE C206/106A 2022 Fall Group 5' final project

url: https://playwithrobot-berkeley.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: Team
    url: /team
  - title: Design/Implementation
    url: /design
  - title: Result/Conclusion
    url: /result
  - title: Appendix
    url: /appendix


social:
  github: PlayWithRobot-Berkeley
#  twitter: brianmaierjr
#  facebook: brianmaierjr
#  email: brimaidesigns@gmail.com
#  linkedin: brianmaierjr

#google_analytics: "UA-58263416-1"

disqus:
#    shortname: brianmaierjr
